dist: bionic

language: go

env: GO111MODULE=on

go:
    - 1.15.x
    - 1.16.x

git:
    depth: 1

script:
    - cd dyndns
    - go test -v ./...
    - go build ./...

notifications:
    email:
        on_success: never
        on_failure: always
